export const UPLOAD_REGION = [
  {
    value: 'SEOUL',
    label: '서울',
    children: [
      { value: 'GANGNAMGU', label: '강남구' },
      { value: 'GANGDONGGU', label: '강동구' },
      { value: 'GANGBUKGU', label: '강북구' },
      { value: 'GANGSEOGU', label: '강서구' },
      { value: 'GWANAKGU', label: '관악구' },
      { value: 'GWANGJINGU', label: '광진구' },
      { value: 'GUROGU', label: '구로구' },
      { value: 'GEUMCHEONGU', label: '금천구' },
      { value: 'NOWONGU', label: '노원구' },
      { value: 'DOBONGGU', label: '도봉구' },
      { value: 'DONGDAEMUNGU', label: '동대문구' },
      { value: 'DONGJAKGU', label: '동작구' },
      { value: 'MAPOGU', label: '마포구' },
      { value: 'SEODAEMUNGU', label: '서대문구' },
      { value: 'SEOCHOGU', label: '서초구' },
      { value: 'SEONGDONGGU', label: '성동구' },
      { value: 'SEONGBUKGU', label: '성북구' },
      { value: 'SONGPAGU', label: '송파구' },
      { value: 'YANGCHEONGU', label: '양천구' },
      { value: 'YEONGDEUNGPOGU', label: '영등포구' },
      { value: 'YONGSANGU', label: '용산구' },
      { value: 'EUNPYEONGGU', label: '은평구' },
      { value: 'JONGNOGU', label: '종로구' },
      { value: 'JUNGGU', label: '중구' },
      { value: 'JUNGRANGGU', label: '중랑구' },
    ],
  },
  {
    value: 'GYEONGGI',
    label: '경기',
    children: [
      { value: 'GAPYEONGGUN', label: '가평군' },
      { value: 'GOYANG_DEOKYANGGU', label: '고양시 덕양구' },
      { value: 'GOYANG_ILSANDONGGU', label: '고양시 일산동구' },
      { value: 'GOYANG_ILSANSEOGU', label: '고양시 일산서구' },
      { value: 'GWACHEONSI', label: '과천시' },
      { value: 'GWANGMYEONGSI', label: '광명시' },
      { value: 'GWANGJUSI', label: '광주시' },
      { value: 'GURISI', label: '구리시' },
      { value: 'GUNPOSI', label: '군포시' },
      { value: 'GIMPOSI', label: '김포시' },
      { value: 'NAMYANGJUSI', label: '남양주시' },
      { value: 'DONGDUCHEONSI', label: '동두천시' },
      { value: 'BUCHEONSI', label: '부천시' },
      { value: 'SEONGNAM_BUNDANGGU', label: '성남시 분당구' },
      { value: 'SEONGNAM_SUJEONGGU', label: '성남시 수정구' },
      { value: 'SEONGNAM_JUNGWONGU', label: '성남시 중원구' },
      { value: 'SUWON_GWONSEONGU', label: '수원시 권선구' },
      { value: 'SUWON_YEONGTONGGU', label: '수원시 영통구' },
      { value: 'SUWON_JANGANGU', label: '수원시 장안구' },
      { value: 'SUWON_PALDALGU', label: '수원시 팔달구' },
      { value: 'SIHEUNGSI', label: '시흥시' },
      { value: 'ANSAN_DANWONGU', label: '안산시 단원구' },
      { value: 'ANSAN_SANGROKGU', label: '안산시 상록구' },
      { value: 'ANSEONGSI', label: '안성시' },
      { value: 'ANYANG_DONGANGU', label: '안양시 동안구' },
      { value: 'ANYANG_MANANGU', label: '안양시 만안구' },
      { value: 'YANGJUSI', label: '양주시' },
      { value: 'YANGPYEONGGUN', label: '양평군' },
      { value: 'YEOJUSI', label: '여주시' },
      { value: 'YEONCHEONGUN', label: '연천군' },
      { value: 'OSANSI', label: '오산시' },
      { value: 'YONGIN_GIHEUNGGU', label: '용인시 기흥구' },
      { value: 'YONGIN_SUJIGU', label: '용인시 수지구' },
      { value: 'YONGIN_CHEOINGU', label: '용인시 처인구' },
      { value: 'UIWANGSI', label: '의왕시' },
      { value: 'UIJEONGBUSI', label: '의정부시' },
      { value: 'ICHEONSI', label: '이천시' },
      { value: 'PAJUSI', label: '파주시' },
      { value: 'PYEONGTAEKSI', label: '평택시' },
      { value: 'POCHEONSI', label: '포천시' },
      { value: 'HANAMSI', label: '하남시' },
      { value: 'HWASEONGSI', label: '화성시' },
    ],
  },
  {
    value: 'INCHEON',
    label: '인천',
    children: [
      { value: 'GANGHWAGUN', label: '강화군' },
      { value: 'GYEYANGGU', label: '계양구' },
      { value: 'NAMDONGGU', label: '남동구' },
      { value: 'DONGGU', label: '동구' },
      { value: 'MICHUHOLGU', label: '미추홀구' },
      { value: 'BUPYEONGGU', label: '부평구' },
      { value: 'SEOGU', label: '서구' },
      { value: 'YEONSUGU', label: '연수구' },
      { value: 'ONGJINGUN', label: '옹진군' },
      { value: 'INCHEON_JUNGGU', label: '중구' },
    ],
  },
  {
    value: 'GANGWON',
    label: '강원',
    children: [
      { value: 'GANGNEUNGSI', label: '강릉시' },
      { value: 'GANGWON_GOSEONGGUN', label: '고성군' },
      { value: 'DONGHAESI', label: '동해시' },
      { value: 'SAMCHEOKSI', label: '삼척시' },
      { value: 'SOKCHOSI', label: '속초시' },
      { value: 'YANGGUGUN', label: '양구군' },
      { value: 'YANGYANGGUN', label: '양양군' },
      { value: 'YEONGWOLGUN', label: '영월군' },
      { value: 'WONJU', label: '원주시' },
      { value: 'INJEGUN', label: '인제군' },
      { value: 'JEONGSEONGUN', label: '정선군' },
      { value: 'CHEORWONGUN', label: '철원군' },
      { value: 'CHUNCHEONSI', label: '춘천시' },
      { value: 'TAEBAEKSI', label: '태백시' },
      { value: 'PYEONGCHANGGUN', label: '평창군' },
      { value: 'HONGCHEONGUN', label: '홍천군' },
      { value: 'HWACHEONGUN', label: '화천군' },
      { value: 'HOENGSEONGGUN', label: '횡성군' },
    ],
  },
  {
    value: 'DAEJEON',
    label: '대전',
    children: [
      { value: 'DAEJEON_DAEDOKGU', label: '대덕구' },
      { value: 'DAEJEON_DONGGU', label: '동구' },
      { value: 'DAEJEON_SEOGU', label: '서구' },
      { value: 'DAEJEON_YUSEONGGU', label: '유성구' },
      { value: 'DAEJEON_JUNGGU', label: '중구' },
    ],
  },
  {
    value: 'SEJONG',
    label: '세종',
    children: [{ value: 'SEJONG', label: '세종시' }],
  },
  {
    value: 'CHUNGNAM',
    label: '충남',
    children: [
      { value: 'GYERYONGSI', label: '계룡시' },
      { value: 'GONGJUSI', label: '공주시' },
      { value: 'GEUMSANGUN', label: '금산군' },
      { value: 'NONSANSI', label: '논산시' },
      { value: 'DANGJINSI', label: '당진시' },
      { value: 'BORYEONGSI', label: '보령시' },
      { value: 'BUYEO', label: '부여군' },
      { value: 'SEOSANSI', label: '서산시' },
      { value: 'SEOCHEONGUN', label: '서천군' },
      { value: 'ASANSI', label: '아산시' },
      { value: 'YESANGUN', label: '예산군' },
      { value: 'CHEONAN_SEOBUKGU', label: '천안시 서북구' },
      { value: 'TAEAN', label: '태안군' },
      { value: 'CHEONGYANG', label: '청양군' },
    ],
  },
  {
    value: 'CHUNGBUK',
    label: '충북',
    children: [
      { value: 'GUAESANGUN', label: '괴산군' },
      { value: 'DANYANGGUN', label: '단양군' },
      { value: 'BOEUNGUN', label: '보은군' },
      { value: 'YEONGDONGGUN', label: '영동군' },
      { value: 'OKCHEONGUN', label: '옥천군' },
      { value: 'EUMSEONGGUN', label: '음성군' },
      { value: 'JECHEONSI', label: '제천시' },
      { value: 'JINCHEONGUN', label: '진천군' },
      { value: 'CHEONGJU_SANGDANGGU', label: '청주시 상당구' },
      { value: 'CHEONGJU_SEOWONGU', label: '청주시 서원구' },
      { value: 'CHEONGJU_CHEONGWONGU', label: '청주시 청원구' },
      { value: 'CHEONGJU_HEUNGDEOKGU', label: '청주시 흥덕구' },
      { value: 'CHUNGJUSI', label: '충주시' },
    ],
  },
  {
    value: 'BUSAN',
    label: '부산',
    children: [
      { value: 'BUSAN_GANGSEOGU', label: '강서구(부산)' },
      { value: 'GEUMJEONGGU', label: '금정구' },
      { value: 'GIJANGGUN', label: '기장군' },
      { value: 'NAMGU', label: '남구' },
      { value: 'BUSAN_DONGGU', label: '동구' },
      { value: 'DONGNAEGU', label: '동래구' },
      { value: 'BUSANJINGU', label: '부산진구' },
      { value: 'BUKGU', label: '북구' },
      { value: 'SASANGGU', label: '사상구' },
      { value: 'SAHAGU', label: '사하구' },
      { value: 'BUSAN_SEOGU', label: '서구' },
      { value: 'SUYEONGGU', label: '수영구' },
      { value: 'YEONJEGU', label: '연제구' },
      { value: 'YEONGDOGU', label: '영도구' },
      { value: 'BUSAN_JUNGGU', label: '중구' },
      { value: 'HAEUNDAEGU', label: '해운대구' },
    ],
  },
  {
    value: 'ULSAN',
    label: '울산',
    children: [
      { value: 'ULSAN_NAMGU', label: '남구' },
      { value: 'ULSAN_DONGGU', label: '동구' },
      { value: 'ULSAN_BUKGU', label: '북구' },
      { value: 'ULJUGUN', label: '울주군' },
      { value: 'ULSAN_JUNGGU', label: '중구' },
    ],
  },
  {
    value: 'GYEONGNAM',
    label: '경남',
    children: [
      { value: 'GEOJESI', label: '거제시' },
      { value: 'GEOCHANGGUN', label: '거창군' },
      { value: 'GYEONGNAM_GOSEONGGUN', label: '고성군' },
      { value: 'GIMHAESI', label: '김해시' },
      { value: 'NAMHAEGUN', label: '남해군' },
      { value: 'MILYANGSI', label: '밀양시' },
      { value: 'SACHEONSI', label: '사천시' },
      { value: 'SANCHEONGGUN', label: '산청군' },
      { value: 'YANGSAN', label: '양산시' },
      { value: 'UIREONGGUN', label: '의령군' },
      { value: 'JINJUSI', label: '진주시' },
      { value: 'CHANGYEONGGUN', label: '창녕군' },
      { value: 'CHANGWON_MASANHAPPOGU', label: '창원시 마산합포구' },
      { value: 'CHANGWON_MASANHOEWONGU', label: '창원시 마산회원구' },
      { value: 'CHANGWON_SEONGSANGU', label: '창원시 성산구' },
      { value: 'CHANGWON_UICHANGGU', label: '창원시 의창구' },
      { value: 'CHANGWON_JINHAEGU', label: '창원시 진해구' },
      { value: 'TONGYEONGSI', label: '통영시' },
      { value: 'HADONGGUN', label: '하동군' },
      { value: 'HAMANGUN', label: '함안군' },
      { value: 'HAMYANGGUN', label: '함양군' },
      { value: 'HAPCHEONGUN', label: '합천군' },
    ],
  },
  {
    value: 'GYEONGBUK',
    label: '경북',
    children: [
      { value: 'GYEONGSANSI', label: '경산시' },
      { value: 'GYEONGJUSI', label: '경주시' },
      { value: 'GORYEONGGUN', label: '고령군' },
      { value: 'GUMISI', label: '구미시' },
      { value: 'GIMCHEONSI', label: '김천시' },
      { value: 'MUNGYEONGSI', label: '문경시' },
      { value: 'BONGHWAGUN', label: '봉화군' },
      { value: 'SANGJUSI', label: '상주시' },
      { value: 'SEONGJUGUN', label: '성주군' },
      { value: 'ANDONGSI', label: '안동시' },
      { value: 'YEONGDEOKGUN', label: '영덕군' },
      { value: 'YEONGYANGGUN', label: '영양군' },
      { value: 'YEONGJUSI', label: '영주시' },
      { value: 'YEONGCHEONSI', label: '영천시' },
      { value: 'YECHEONGUN', label: '예천군' },
      { value: 'ULLEUNGGUN', label: '울릉군' },
      { value: 'ULJINGUN', label: '울진군' },
      { value: 'UISEONGGUN', label: '의성군' },
      { value: 'CHEONGDOGUN', label: '청도군' },
      { value: 'CHEONGSONGGUN', label: '청송군' },
      { value: 'CHILGOKGUN', label: '칠곡군' },
      { value: 'POHANG_NAMGU', label: '포항시 남구' },
      { value: 'POHANG_BUKGU', label: '포항시 북구' },
    ],
  },
  {
    value: 'DAEGU',
    label: '대구',
    children: [
      { value: 'GUNWEEGUN', label: '군위군' },
      { value: 'DAEGU_NAMGU', label: '남구' },
      { value: 'DAEGU_DALSEOGU', label: '달서구' },
      { value: 'DAEGU_DALSEONGGUN', label: '달성군' },
      { value: 'DAEGU_DONGGU', label: '동구' },
      { value: 'DAEGU_BUKGU', label: '북구' },
      { value: 'DAEGU_SEOGU', label: '서구' },
      { value: 'DAEGU_SUSEONGGU', label: '수성구' },
      { value: 'DAEGU_JUNGGU', label: '중구' },
    ],
  },
  {
    value: 'GWANGJU',
    label: '광주',
    children: [
      { value: 'GWANGJU_GWANGSANGU', label: '광산구' },
      { value: 'GWANGJU_NAMGU', label: '남구' },
      { value: 'GWANGJU_DONGGU', label: '동구' },
      { value: 'GWANGJU_BUKGU', label: '북구' },
      { value: 'GWANGJU_SEOGU', label: '서구' },
    ],
  },
  {
    value: 'JEONNAM',
    label: '전남',
    children: [
      { value: 'GANGJINGUN', label: '강진군' },
      { value: 'GOHEUNGGUN', label: '고흥군' },
      { value: 'GOKSEONGGUN', label: '곡성군' },
      { value: 'GWANGYANGSI', label: '광양시' },
      { value: 'GURYEOGUN', label: '구례군' },
      { value: 'NAJUSI', label: '나주시' },
      { value: 'DAMYANGGUN', label: '담양군' },
      { value: 'MOKPOSI', label: '목포시' },
      { value: 'MUANGUN', label: '무안군' },
      { value: 'BOSEONGGUN', label: '보성군' },
      { value: 'SUNCHEONSI', label: '순천시' },
      { value: 'SHINANGUN', label: '신안군' },
      { value: 'YEOSUSI', label: '여수시' },
      { value: 'YEONGGWANGGUN', label: '영광군' },
      { value: 'YEONGAMGUN', label: '영암군' },
      { value: 'WANDO', label: '완도군' },
      { value: 'JANGSEONG', label: '장성군' },
      { value: 'JANGHEUNG', label: '장흥군' },
      { value: 'JINDOGUN', label: '진도군' },
      { value: 'HAMPYEONGGUN', label: '함평군' },
      { value: 'HAENAMGUN', label: '해남군' },
      { value: 'HWASUNGUN', label: '화순군' },
    ],
  },
  {
    value: 'JEONBUK',
    label: '전북',
    children: [
      { value: 'GOCHANGGUN', label: '고창군' },
      { value: 'GUNSAN', label: '군산시' },
      { value: 'GIMJESI', label: '김제시' },
      { value: 'NAMWONSI', label: '남원시' },
      { value: 'MUJUGUN', label: '무주군' },
      { value: 'BUAN', label: '부안군' },
      { value: 'SUNCHEON', label: '순창군' },
      { value: 'WANJU', label: '완주군' },
      { value: 'IKSANSI', label: '익산시' },
      { value: 'IMSIL', label: '임실군' },
      { value: 'JANGSU', label: '장수군' },
      { value: 'JEONJU_DEOKJINGU', label: '전주시 덕진구' },
      { value: 'JEONJU_WANSANGU', label: '전주시 완산구' },
      { value: 'JEONGEUP', label: '정읍시' },
      { value: 'JINAN', label: '진안군' },
    ],
  },
  {
    value: 'JEJU',
    label: '제주',
    children: [
      { value: 'JEJU_SEOGWIPOSI', label: '서귀포시' },
      { value: 'JEJU_JEJUSI', label: '제주시' },
    ],
  },
];
