import type { Metadata } from 'next';

import Providers from './providers';

import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
