export const areaMapper: Record<string, string> = {
  ALL: '전국',
  SEOUL: '서울',
  GYEONGGI: '경기',
  INCHEON: '인천',
  GANGWON: '강원',
  DAEJEON: '대전',
  SEJONG: '세종',
  CHUNGNAM: '충남',
  CHUNGBUK: '충북',
  BUSAN: '부산',
  ULSAN: '울산',
  GYEONGNAM: '경남',
  GYEONGBUK: '경북',
  DAEGU: '대구',
  GWANGJU: '광주',
  JEONNAM: '전남',
  JEONBUK: '전북',
  JEJU: '제주',
} as const;

export const subAreaMapper: Record<string, string> = {
  SEOUL_ALL: '서울 전체',
  GEUMCHEONGU: '금천구',
  NOWONGU: '노원구',
  DOBONGGU: '도봉구',
  DONGDAEMUNGU: '동대문구',
  DONGJAKGU: '동작구',
  MAPOGU: '마포구',
  SEODAEMUNGU: '서대문구',
  SEOCHOGU: '서초구',
  SEONGDONGGU: '성동구',
  SEONGBUKGU: '성북구',
  SONGPAGU: '송파구',
  YANGCHEONGU: '양천구',
  YEONGDEUNGPOGU: '영등포구',
  YONGSANGU: '용산구',
  EUNPYEONGGU: '은평구',
  JONGNOGU: '종로구',
  JUNGGU: '중구',
  JUNGRANGGU: '중랑구',
  GWANGJINGU: '광진구',
  GANGNAMGU: '강남구',
  GANGDONGGU: '강동구',
  GWANAKGU: '관악구',
  GUROGU: '구로구',
  GANGBUKGU: '강북구',
  GANGSEOGU: '강서구',
};
