export const REGION_MAPPER: Record<string, string> = {
  ALL: '전국',
  SEOUL: '서울',
  GYEONGGI: '경기',
  INCHEON: '인천',
  GANGWON: '강원',
  DAEJEON: '대전',
  SEJONG: '세종',
  CHUNGNAM: '충남',
  CHUNGBUK: '충북',
  BUSAN: '부산',
  ULSAN: '울산',
  GYEONGNAM: '경남',
  GYEONGBUK: '경북',
  DAEGU: '대구',
  GWANGJU: '광주',
  JEONNAM: '전남',
  JEONBUK: '전북',
  JEJU: '제주',
} as const;

export const AREA_MAPPER: Record<string, string> = {
  // 서울 부분 (기존 항목)
  SEOUL_ALL: '전체',
  GEUMCHEONGU: '금천구',
  NOWONGU: '노원구',
  DOBONGGU: '도봉구',
  DONGDAEMUNGU: '동대문구',
  DONGJAKGU: '동작구',
  MAPOGU: '마포구',
  SEODAEMUNGU: '서대문구',
  SEOCHOGU: '서초구',
  SEONGDONGGU: '성동구',
  SEONGBUKGU: '성북구',
  SONGPAGU: '송파구',
  YANGCHEONGU: '양천구',
  YEONGDEUNGPOGU: '영등포구',
  YONGSANGU: '용산구',
  EUNPYEONGGU: '은평구',
  JONGNOGU: '종로구',
  JUNGGU: '중구',
  JUNGRANGGU: '중랑구',
  GWANGJINGU: '광진구',
  GANGNAMGU: '강남구',
  GANGDONGGU: '강동구',
  GWANAKGU: '관악구',
  GUROGU: '구로구',
  GANGBUKGU: '강북구',
  GANGSEOGU: '강서구',

  // 경기
  GYEONGGI_ALL: '전체',
  GAPYEONGGUN: '가평군',
  GOYANG_DEOKYANGGU: '고양 덕양구',
  GOYANG_ILSANDONGGU: '고양 일산동구',
  GOYANG_ILSANSEOGU: '고양 일산서구',
  GWACHEONSI: '과천시',
  GWANGMYEONGSI: '광명시',
  GWANGJUSI: '광주시',
  GURISI: '구리시',
  GUNPOSI: '군포시',
  GIMPOSI: '김포시',
  NAMYANGJUSI: '남양주시',
  DONGDUCHEONSI: '동두천시',
  BUCHEONSI: '부천시',
  SEONGNAM_BUNDANGGU: '성남 분당구',
  SEONGNAM_SUJEONGGU: '성남 수정구',
  SEONGNAM_JUNGWONGU: '성남 중원구',
  SUWON_GWONSEONGU: '수원 권선구',
  SUWON_YEONGTONGGU: '수원 영통구',
  SUWON_JANGANGU: '수원 장안구',
  SUWON_PALDALGU: '수원 팔달구',
  SIHEUNGSI: '시흥시',
  ANSAN_DANWONGU: '안산 단원구',
  ANSAN_SANGROKGU: '안산 상록구',
  ANSEONGSI: '안성시',
  ANYANG_DONGANGU: '안양 동안구',
  ANYANG_MANANGU: '안양 만안구',
  YANGJUSI: '양주시',
  YANGPYEONGGUN: '양평군',
  YEOJUSI: '여주시',
  YEONCHEONGUN: '연천군',
  OSANSI: '오산시',
  YONGIN_GIHEUNGGU: '용인 기흥구',
  YONGIN_SUJIGU: '용인 수지구',
  YONGIN_CHEOINGU: '용인 처인구',
  UIWANGSI: '의왕시',
  UIJEONGBUSI: '의정부시',
  ICHEONSI: '이천시',
  PAJUSI: '파주시',
  PYEONGTAEKSI: '평택시',
  POCHEONSI: '포천시',
  HANAMSI: '하남시',
  HWASEONGSI: '화성시',

  // 인천
  INCHEON_ALL: '전체',
  GANGHWAGUN: '강화군',
  GYEYANGGU: '계양구',
  NAMDONGGU: '남동구',
  DONGGU: '동구',
  MICHUHOLGU: '미추홀구',
  BUPYEONGGU: '부평구',
  SEOGU: '서구',
  YEONSUGU: '연수구',
  ONGJINGUN: '옹진군',
  INCHEON_JUNGGU: '인천 중구',

  // 강원
  GANGWON_ALL: '전체',
  GANGNEUNGSI: '강릉시',
  GANGWON_GOSEONGGUN: '강원 고성군',
  DONGHAESI: '동해시',
  SAMCHEOKSI: '삼척시',
  SOKCHOSI: '속초시',
  YANGGUGUN: '양구군',
  YANGYANGGUN: '양양군',
  YEONGWOLGUN: '영월군',
  WONJU: '원주시',
  INJEGUN: '인제군',
  JEONGSEONGUN: '정선군',
  CHEORWONGUN: '철원군',
  CHUNCHEONSI: '춘천시',
  TAEBAEKSI: '태백시',
  PYEONGCHANGGUN: '평창군',
  HONGCHEONGUN: '홍천군',
  HWACHEONGUN: '화천군',
  HOENGSEONGGUN: '횡성군',

  // 대전
  DAEJEON_ALL: '전체',
  DAEJEON_DAEDOKGU: '대전 대덕구',
  DAEJEON_DONGGU: '대전 동구',
  DAEJEON_SEOGU: '대전 서구',
  DAEJEON_YUSEONGGU: '대전 유성구',
  DAEJEON_JUNGGU: '대전 중구',

  // 세종
  SEJONG: '세종',

  // 충남
  CHUNGNAM_ALL: '전체',
  GYERYONGSI: '계룡시',
  GONGJUSI: '공주시',
  GEUMSANGUN: '금산군',
  NONSANSI: '논산시',
  DANGJINSI: '당진시',
  BORYEONGSI: '보령시',
  BUYEO: '부여군',
  SEOSANSI: '서산시',
  SEOCHEONGUN: '서천군',
  ASANSI: '아산시',
  YESANGUN: '예산군',
  CHEONAN_SEOBUKGU: '천안 서북구',
  TAEAN: '태안군',
  CHEONGYANG: '청양군',

  // 충북
  CHUNGBUK_ALL: '전체',
  GUAESANGUN: '괴산군',
  DANYANGGUN: '단양군',
  BOEUNGUN: '보은군',
  YEONGDONGGUN: '영동군',
  OKCHEONGUN: '옥천군',
  EUMSEONGGUN: '음성군',
  JECHEONSI: '제천시',
  JINCHEONGUN: '진천군',
  CHEONGJU_SANGDANGGU: '청주 상당구',
  CHEONGJU_SEOWONGU: '청주 서원구',
  CHEONGJU_CHEONGWONGU: '청주 청원구',
  CHEONGJU_HEUNGDEOKGU: '청주 흥덕구',
  CHUNGJUSI: '충주시',

  // 경남
  GYEONGNAM_ALL: '전체',
  GEOJESI: '거제시',
  GEOCHANGGUN: '거창군',
  GYEONGNAM_GOSEONGGUN: '경남 고성군',
  GIMHAESI: '김해시',
  NAMHAEGUN: '남해군',
  MILYANGSI: '밀양시',
  SACHEONSI: '사천시',
  SANCHEONGGUN: '산청군',
  YANGSAN: '양산시',
  UIREONGGUN: '의령군',
  JINJUSI: '진주시',
  CHANGYEONGGUN: '창녕군',
  CHANGWON_MASANHAPPOGU: '창원 마산합포구',
  CHANGWON_MASANHOEWONGU: '창원 마산회원구',
  CHANGWON_SEONGSANGU: '창원 성산구',
  CHANGWON_UICHANGGU: '창원 의창구',
  CHANGWON_JINHAEGU: '창원 진해구',
  TONGYEONGSI: '통영시',
  HADONGGUN: '하동군',
  HAMANGUN: '함안군',
  HAMYANGGUN: '함양군',
  HAPCHEONGUN: '합천군',

  // 경북
  GYEONGBUK_ALL: '전체',
  GYEONGSANSI: '경산시',
  GYEONGJUSI: '경주시',
  GORYEONGGUN: '고령군',
  GUMISI: '구미시',
  GIMCHEONSI: '김천시',
  MUNGYEONGSI: '문경시',
  BONGHWAGUN: '봉화군',
  SANGJUSI: '상주시',
  SEONGJUGUN: '성주군',
  ANDONGSI: '안동시',
  YEONGDEOKGUN: '영덕군',
  YEONGYANGGUN: '영양군',
  YEONGJUSI: '영주시',
  YEONGCHEONSI: '영천시',
  YECHEONGUN: '예천군',
  ULLEUNGGUN: '울릉군',
  ULJINGUN: '울진군',
  UISEONGGUN: '의성군',
  CHEONGDOGUN: '청도군',
  CHEONGSONGGUN: '청송군',
  CHILGOKGUN: '칠곡군',
  POHANG_NAMGU: '포항 남구',
  POHANG_BUKGU: '포항 북구',

  // 전남
  JEONNAM_ALL: '전체',
  GANGJINGUN: '강진군',
  GOHEUNGGUN: '고흥군',
  GOKSEONGGUN: '곡성군',
  GWANGYANGSI: '광양시',
  GURYEOGUN: '구례군',
  NAJUSI: '나주시',
  DAMYANGGUN: '담양군',
  MOKPOSI: '목포시',
  MUANGUN: '무안군',
  BOSEONGGUN: '보성군',
  SUNCHEONSI: '순천시',
  SHINANGUN: '신안군',
  YEOSUSI: '여수시',
  YEONGGWANGGUN: '영광군',
  YEONGAMGUN: '영암군',
  WANDO: '완도군',
  JANGSEONG: '장성군',
  JANGHEUNG: '장흥군',
  JINDOGUN: '진도군',
  HAMPYEONGGUN: '함평군',
  HAENAMGUN: '해남군',
  HWASUNGUN: '화순군',

  // 전북
  JEONBUK_ALL: '전체',
  GOCHANGGUN: '고창군',
  GUNSAN: '군산시',
  GIMJESI: '김제시',
  NAMWONSI: '남원시',
  MUJUGUN: '무주군',
  BUAN: '부안군',
  SUNCHEON: '순창군',
  WANJU: '완주시',
  IKSANSI: '익산시',
  IMSIL: '임실군',
  JANGSU: '장수군',
  JEONJU_DEOKJINGU: '전주 덕진구',
  JEONJU_WANSANGU: '전주 완산구',
  JEONGEUP: '정읍시',
  JINAN: '진안군',

  // 대구
  DAEGU_ALL: '전체',
  GUNWEEGUN: '군위군',
  DAEGU_NAMGU: '대구 남구',
  DAEGU_DALSEOGU: '대구 달서구',
  DAEGU_DALSEONGGUN: '대구 달성군',
  DAEGU_DONGGU: '대구 동구',
  DAEGU_BUKGU: '대구 북구',
  DAEGU_SEOGU: '대구 서구',
  DAEGU_SUSEONGGU: '대구 수성구',
  DAEGU_JUNGGU: '대구 중구',

  // 광주
  GWANGJU_ALL: '전체',
  GWANGJU_GWANGSANGU: '광주 광산구',
  GWANGJU_NAMGU: '광주 남구',
  GWANGJU_DONGGU: '광주 동구',
  GWANGJU_BUKGU: '광주 북구',
  GWANGJU_SEOGU: '광주 서구',

  // 부산
  BUSAN_ALL: '전체',
  BUSAN_GANGSEOGU: '부산 강서구',
  GEUMJEONGGU: '금정구',
  GIJANGGUN: '기장군',
  NAMGU: '부산 남구',
  BUSAN_DONGGU: '부산 동구',
  DONGNAEGU: '동래구',
  BUSANJINGU: '부산진구',
  BUKGU: '부산 북구',
  SASANGGU: '사상구',
  SAHAGU: '사하구',
  BUSAN_SEOGU: '부산 서구',
  SUYEONGGU: '수영구',
  YEONJEGU: '연제구',
  YEONGDOGU: '영도구',
  BUSAN_JUNGGU: '부산 중구',
  HAEUNDAEGU: '해운대구',

  // 울산
  ULSAN_ALL: '전체',
  ULSAN_NAMGU: '울산 남구',
  ULSAN_DONGGU: '울산 동구',
  ULSAN_BUKGU: '울산 북구',
  ULJUGUN: '울주군',
  ULSAN_JUNGGU: '울산 중구',

  // 제주
  JEJU_SEOGWIPOSI: '제주 서귀포시',
  JEJU_JEJUSI: '제주 제주시',

  // 기타
  NONE: '없음',
} as const;

export const AREA_ALL = [
  'SEOUL_ALL',
  'GYEONGGI_ALL',
  'INCHEON_ALL',
  'GANGWON_ALL',
  'DAEJEON_ALL',
  'CHUNGNAM_ALL',
  'CHUNGBUK_ALL',
  'GYEONGNAM_ALL',
  'GYEONGBUK_ALL',
  'JEONNAM_ALL',
  'JEONBUK_ALL',
  'DAEGU_ALL',
  'GWANGJU_ALL',
  'BUSAN_ALL',
  'ULSAN_ALL',
] as const;

export const GENDER = [
  { label: '남성', value: 'MALE' },
  { label: '여성', value: 'FEMALE' },
] as const;

export const MATCH_TYPE_OPTIONS = [
  { label: '전체', value: 'ALL' },
  { label: '대면', value: 'OFFLINE' },
  { label: '비대면', value: 'ONLINE' },
] as const;

// Banner
export const BANNER_LENGTH = 4;
export const SLIDE_SPEED = 1.2;
